# src/main/resources/application.properties

# Default to local profile when running on your computer
spring.profiles.active=local

# SERVER CONFIGURATION
# Koyeb will inject its own PORT here. On your laptop, it defaults to 8080.
server.port=${PORT:8080}

# HIBERNATE / JPA SETTINGS (Shared across both environments)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-circular-references=true